### ISSUE TITLE
Save after close

### ISSUE THREAD

**Issue by basketofminks** [qzb/dustman#1]
The one thing that makes Tab Wrangler a million times better is that it saves the closed tabs in the menu if you have to restart the browser or computer. I, and I assume most people who use this is as an alternative to having hundreds of tabs and/or windows up at once. It would be really great if they were still there next session.

**Comment by qzb** [comment]
I was planning to add such feature but it wasn't important for me so finally I given up on it. I will add it in next version of addon.

**Comment by qzb** [comment]
I've released new version with requested feature, but it will take a while to pass review process. For now you can download new version here: https://github.com/qzb/dustman/releases/tag/1.1.0

**Comment by basketofminks** [comment]
That's really above and beyond, thank you!

Date: Mon, 8 Jun 2015 09:57:49 -0700
