### ISSUE TITLE
Toolbar button icons for "small" and "normal" icons sizes reversed

### ISSUE THREAD

**Issue by csmarshall** [qzb/dustman#10]
In my config this is what "small" icons look like:
<img width="90" alt="screen shot 2016-05-23 at 9 56 39 am" src="https://cloud.githubusercontent.com/assets/1200112/15478065/ef246dd6-20cc-11e6-9090-a7762f73e50b.png">

Meanwhile "normal" icons look like:
<img width="112" alt="screen shot 2016-05-23 at 9 56 59 am" src="https://cloud.githubusercontent.com/assets/1200112/15478064/ef0a3f6a-20cc-11e6-87b8-545166a01313.png">

Using dustman 1.1.0.1-signed, on mac FF 46.0.1

**Comment by qzb** [comment]
What you mean by "small icons"? And could you make screenshot with dustman button next to some standard button like "homepage"?

**Comment by csmarshall** [comment]
Sure, here you go, the main difference between the "normal" size icon and the "small" size icon is the spacing around the icon itself. 

"Normal"
<img width="134" alt="screen shot 2016-06-02 at 9 18 08 am" src="https://cloud.githubusercontent.com/assets/1200112/15752483/2c4de858-28a3-11e6-9940-7a689305e601.png">

"Small"
<img width="102" alt="screen shot 2016-06-02 at 9 17 57 am" src="https://cloud.githubusercontent.com/assets/1200112/15752482/2c4e40dc-28a3-11e6-9718-31216c8c76a5.png">

Also oddly if you enable the text below for the icon, in the small or large size the correct icon size is shown (no matter the button size)

<img width="347" alt="screen shot 2016-06-02 at 9 21 04 am" src="https://cloud.githubusercontent.com/assets/1200112/15752535/668fd670-28a3-11e6-9760-eb6e10ae9b20.png">

**Comment by qzb** [comment]
I must be blind, I cannot find any option for toggling icons size. Do you use some addon to achieve that?

**Comment by csmarshall** [comment]
Nope, just go and say you are going to "customize" your tool bar, for me on a mac it's "View -> Toolbars -> Customize" then in the lower left corner of the page that pops up you can give your button size, and whether the icons have text under them, tabs on top etc.
<img width="500" alt="screen shot 2016-06-07 at 4 50 05 pm" src="https://cloud.githubusercontent.com/assets/1200112/15878461/f7a059c0-2ccf-11e6-9dff-d18727bc935d.png">

**Comment by qzb** [comment]
I don't have these options. Which version of Firefox are you using? And what extensions have you installed?

**Comment by csmarshall** [comment]
It's firefox 47, but with "classic theme restorer" installed, don't know why that makes a difference, but I'm now sure it does.  I thought I saw some other fixes for other extensions, but I may be wrong, leaving it open for @qzb to decide whether this is a thing to be "fixed" or not

**Comment by qzb** [comment]
I've fixed it, new version should be approved tomorrow or day after tomorrow. Currently you can install it manually: https://addons.mozilla.org/pl/firefox/addon/dustman/versions/?page=1#version-1.2.1
