### ISSUE TITLE
Add search box to menu dropdown to quickly search titles of closed tabs.

### ISSUE THREAD

**Issue by csmarshall** [qzb/dustman#15]
Pretty simple request, but I'm sure not easy to implement, a search field at the bottom of the popup window, similar to how you can search for titles if you hit CMD+SHIFT+E to show all tab groups. Should a tab be closed you can find it and reopen it with just searching.

**Comment by mbid** [comment]
I think you can just use firefox's normal history search functionality if you really need it.
