### ISSUE TITLE
Favicon Disappeared

### ISSUE THREAD

**Issue by Riajyuu** [qzb/dustman#18]
Favicon disappeared for some entries in Dustman's panel (autoly closed tabs) on FF 49a.

**Comment by qzb** [comment]
Favicons disappeared during single browser session or after restart? And could you provide me some url of website which favicon disappeared?

**Comment by Riajyuu** [comment]
That's during a single session.
1.Open 49a Home Page, https://userstyles.org/styles/browse/browser, and about:addons
2.Adjust addon setting so that Dustman will start at that case
3.Wait
Now in the panel Home page favicon disappeared.
Samely I find out some more like https://addons.mozilla.org/en-US/firefox/addon/dustman/?src=ss
about:addons and much more.
Plus, it seems happening on basically all URLs than specific ones.

**Comment by qzb** [comment]
Thanks, I'll look into that.

**Comment by mbid** [comment]
Does this also happen in the new version?

**Comment by Riajyuu** [comment]
Not really, thx
