### ISSUE TITLE
Issue with Gmail's web client

### ISSUE THREAD

**Issue by cwsailor** [qzb/dustman#2]
Each time I use Gmail's web-based client it seems that a huge number of redundant instances of Gmail's tab show up in the Dustman list.  I think this only began to happen once I started composing an e-mail in the browser, meaning it may be Gmail's auto-save function that is triggering this.  In any case, it is pretty frustrating if you want to try to find a legitimate closed tab within all those instances of Gmail.  I hope this gets sorted out, as I'm a big fan of your add-on!

**Comment by cwsailor** [comment]
Looks like Facebook's auto-refresh is triggering this behavior as well: after a few hours with both Gmail and Facebook tabs open, my Dustman menu has dozens of redundant instances of each.  Neither tab has actually ever been closed by Dustman, as both are protected.

**Comment by qzb** [comment]
So tabs are still open, but inside of panel there are plenty of links to them. And, I assume, both tabs prevents closing with some kind of alert, aren't they? If so, I know a bug which could be responsible for this behaviour.

**Comment by qzb** [comment]
Fixed (I hope). You download new version [here](https://github.com/qzb/dustman/releases/tag/1.1.0) or wait for automatic update after finish of review process.

**Comment by cwsailor** [comment]
That seems to have solved it completely -- nice work!

**Comment by qzb** [comment]
I'm glad to hear that.
