### ISSUE TITLE
Multiprocess compatibility

### ISSUE THREAD

**Issue by henrikq** [qzb/dustman#22]
It seems that dustman blocks multiprocess mode. 

Check about:support and look for a number higher than 0 in the "Multiprocess Windows" entry. If you would like to opt-in, open about:config and toggle browser.tabs.remote.autostart to true. On your next restart, e10s should be active.

source: https://wiki.mozilla.org/Electrolysis#Firefox_Release

**Comment by harl** [comment]
Works fine for me. I've had e10s enabled for quite some time and Dustman hasn't interfered with it.

**Comment by henrikq** [comment]
have you checked about:support?
![dustman disables multiprocess](https://cloud.githubusercontent.com/assets/13659903/22102859/4397ecce-de39-11e6-9735-999bb5cab034.png)

**Comment by harl** [comment]
Of course I checked about:support ..
I'm on the Nightly channel (FF 53.0a1) and it still says "Multiprocess Windows 	1/1 (Enabled by user)" with Dustman loaded.

**Comment by henrikq** [comment]
maybe its the FF version then ...

**Comment by mbid** [comment]
Fixed by aaf3737ac4453c373395a521524c4ebede81a89a.
