### ISSUE TITLE
Question, possible to make the addon auto-close last viewed tab?

### ISSUE THREAD

**Issue by D4n2021** [qzb/dustman#23]
So in Yahoo mail, I click a link in my mail and that link opens in new tab (always). Can I enable in this addon that as soon as a Yahoo Tab goes in background, it will be closed? :)

**Comment by qzb** [comment]
Unfortunately currently this isn't possible and I don't see any way to fit such a feature to this add-on :/

**Comment by D4n2021** [comment]
ok
