### ISSUE TITLE
Compatibility with the latest FF versions (Nightly)

### ISSUE THREAD

**Issue by harl** [qzb/dustman#25]
Been using Dustman for a while now and it's worked fine until about 3 weeks ago.
I don't remember what changed then exactly, but I'm assuming it has something to do with the changes Moz made with the latest dev version of Firefox (Nightly 55.0a1).
It seems Dustman still closes tabs, but they don't appear in the drop-down list at all.
The list is just blank - except for the pause/resume button.

Would be great if you could take a look at this sometime.
(Come FF 55 in a few months, it may need fixing anyway.)

**Comment by mbid** [comment]
Fixed by aaf3737ac4453c373395a521524c4ebede81a89a.
