### ISSUE TITLE
close all tabs, except the pinned ones

### ISSUE THREAD

**Issue by Ogniute** [qzb/dustman#3]
Hey qzb, 

i think there is an issue in your implementation. 

I work with the firefox 40.0 on mac os x. If i set the timout to 1 minute, it will close all tabs after one minute of one tab. The pinned tabs are still open.

**Comment by Ogniute** [comment]
Is it correct, that you just set the current time of an action in the tab at the events: "activate" tab and "deactivate" tab? i think you have ti check whether there is any interaction in the tab.

**Comment by qzb** [comment]
Nope, it should simply not close active tab.
