### ISSUE TITLE
Feature Request: Pale Moon support

### ISSUE THREAD

**Issue by Lew-Rockwell-Fan** [qzb/dustman#31]
Love to see this on PM. I'm using Window & Tab Limiter but this looks like it might have more flexible options. Ideally I'd like to auto close the tab-least-recently-used when the total number exceeds a settable N.

**Comment by mbid** [comment]
Hi there,
unfortunately, I'm not a Pale Moon user. Does the last 1.x version work in PM? Old versions can be downloaded at https://addons.mozilla.org/en-US/firefox/addon/dustman/versions/.

**Comment by Lew-Rockwell-Fan** [comment]
The last 1.x has that "This add-on is not compatible with your version of Firefox." message beside it, but the oldest one on the  page doesn't. But it won't install because jetpack/sdk is not supported by PM. Thanks.

**Comment by mbid** [comment]
Unfortunately, that means that the addon has to be rewritten from scratch. I don't think you can salvage much from either the 1.x or 2.x versions of dustman. The rewrite would be incompatible with firefox >= 57, so I think this should be a separate project. I'm not a PM user, so I don't really have any incentive to work on that.

**Comment by JustOff** [comment]
@Lew-Rockwell-Fan
[Dustman 1.2.1](https://addons.mozilla.org/en-US/firefox/addon/dustman/versions/1.2.1) works just fine with Pale Moon 27.x if you download and install it from local file using [Moon Tester Tool](https://addons.palemoon.org/addon/moon-tester-tool/).

@mbid 
Actually it's easy to build a native version of Dustman for Pale Moon from the 1.x tree, all you need is just [add Pale Moon to the list of engines in package.json](http://developer.palemoon.org/Add-ons:Extensions/Jetpack).

**Comment by mbid** [comment]
I suggest you fork this repo, roll back  master to 1.2.1 and continue from there. Because the two verions of the addons barely share code, I don't think it makes sense to have them live within the same repository.

The only overlap I see is the the GUI currently, and even that is implemented differently (e.g. simple prefs vs. dedicated settings page). If you can make the old version use the current GUI, I'll be happy to merge again.

**Comment by Lew-Rockwell-Fan** [comment]
@JustOff Thanks. I may try that after I next backup my system & get FEBE working to backup PM. Because last time I tried it Moon Tester totally borked my PM. Can't say I wasn't warned - it has a pretty strongly worded warning to the effect that it may break PM, erase data, and attract Russian Spies. No, wait, that last was in the Washington Post comics section.  What kind of system did you do it on? Mine is an ultralight Ubuntu with X11 & Openbox & very little else, kinda of like Lubuntu's skinny cousin.
