### ISSUE TITLE
Feature request: remove tab from bin when resumed

### ISSUE THREAD

**Issue by AntonioGHub** [qzb/dustman#32]
I believe It would be quite useful to have the page removed from the bin when you restore it (click on it and it gets open in the browser).

**Comment by mbid** [comment]
Hi Antonio, I think agree with you. But as you describe this feature, I'd think dustman already does this. Could you give an example of the behavior you're expecting?

**Comment by AntonioGHub** [comment]
Whoops, you are right, it is removed upon restore.

I was mislead by the fact that the tab doesn't disappear from the "baloon" (the list) immediately when you click it. To see that it disappeared you have to reopen the list.

I guess that the GUI refreshes the list when you click on the "trash" icon, and probably would be more intuitive to have the GUI updated straight away, but provided that you are aware, it is fine as it is.

Thanks
