### ISSUE TITLE
Cutom timeout

### ISSUE THREAD

**Issue by cyclingzealot** [qzb/dustman#4]
The documentation at https://addons.mozilla.org/en-US/firefox/addon/dustman/?src=cb-dl-created says "Dustman closes tabs which have not been used within last 20 minutes".

I would use the extension if the time-out was customizable as I'd sooner set it to 24 hours.

**Comment by qzb** [comment]
This time-out is already customizable. To change it open Firefox extension's settings (_about:addons_) and click on Dustman's _options_ button.
