### ISSUE TITLE
Firefox Add-Ons Version

### ISSUE THREAD

**Issue by gsauthof** [qzb/dustman#41]
Can you clarify what's the current status of this addon in the Firefox Add-Ons repository?

Currently [it's listed there](https://addons.mozilla.org/en-US/firefox/addon/dustman/) as:

```
Dustman - AutoClose Tabs
by qzb, Firefox user 13300030
```

I'm a little bit concerned about co-maintainer `Firefox user 13300030` - which looks kind of suspicious.

So what's the deal with that?

Ok, after looking at the activity in this repository and [this comment](https://github.com/qzb/dustman/issues/37#issuecomment-495997258) this addon seems to be unmaintained.

Perhaps it then makes sense to indicate this fact at a prominent location in the readme and on dustman's firefox add-ons page.

**Comment by mbid** [comment]
Hi there, I'm firefox user 1300030. Looks like mozilla changed something about how they manage accounts and my nick got deleted in the process. I still have access to the account though.

Regarding maintenance: I'm still using the addon when I'm on firefox desktop and might fix bugs there, but I don't have plans on adding new features/fixing android issues.
