### ISSUE TITLE
The Holy Grail ?

### ISSUE THREAD

**Issue by Abiologist** [qzb/dustman#8]
Dear Sir, 
This could be the Holy Grail of Firefox security, which I've been looking for for years. Together with Private Tab I can set firefox to open with a private tab on startup (and all further tabs are private as well), and then if I forget to log off of eg. gmail, Dustman closes Firefox completely after some time, and my gmail cannot be seen or accessed. The problem is that at the moment it works a little too well: with Mac Mavericks and Firefox 42 when I set minimum number of tabs to zero (I want Firefox to close completely if inactive) and the time to 2 minutes, then after 2 minutes instead of only inactive tabs closing the tab screen I'm using to actively play chess closes as well (ie. all screens close) !! - should it do this even though I'm actively clicking on this screen every few seconds ? (this also happens if I actively move a scroll bar up and down every few seconds using a different screen - all screens still close). I would much prefer for any screen that I'm actively using (meaning one that I'm clicking on or moving something on) to stay open - is this possible ? Many thanks.

**Comment by qzb** [comment]
It is possible and it is quite simply to do. I will definitely add this feature in next release.
